// Generated by Finicky Kickstart
// Save as ~/.finicky.js
//
// Tool to add rules: https://finicky-kickstart.now.sh
// or https://finicky-kickstart.vercel.app/

module.exports = {
  defaultBrowser: ["Firefox", "Google Chrome"],
  handlers: [
    {
      match: /^https?:\/\/datavant.*\.$/,
      browser: "Google Chrome",
    },
    {
      match: /^https?:\/\/stripe\.com$/,
      browser: "Firefox",
    },
    {
      match: /zoom\.us\/join/,
      browser: "us.zoom.xos",
    },
    {
      // Open any link clicked in Mail & Outlook in Google Chrome
      match: ({ opener, keys }) => {
        return ["Slack"].includes(opener.name) && keys.option;
      },
      browser: "Google Chrome",
    },
  ],
  rewrite: [
    {
      match(all) {
        finicky.log(JSON.stringify(all, null, 2));
        return false;
      },
      url: ({ url }) => url,
    },
    {
      match: ({ url }) => url.host.includes("zoom.us") && url.pathname.includes("/j/"),
      url({ url }) {
        try {
          var pass = "&pwd=" + url.search.match(/pwd=(\w*)/)[1];
        } catch {
          var pass = "";
        }
        var conf = "confno=" + url.pathname.match(/\/j\/(\d+)/)[1];
        return {
          search: conf + pass,
          pathname: "/join",
          protocol: "zoommtg",
        };
      },
    },
  ],
};
